apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/ingress.class: k0s
spec:
  ingressClassName: k0s
  rules:
    - host: example
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: hub
                port:
                  number: 80
